# Generated by Django 4.2.3 on 2023-07-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnswersABCModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="Telegram User ID")),
                ("answers", models.JSONField()),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "ABC Model Answer",
                "verbose_name_plural": "ABC Model Answers",
            },
        ),
        migrations.CreateModel(
            name="AnswersWorkList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="Telegram User ID")),
                ("answers", models.JSONField()),
                ("date", models.DateField()),
            ],
            options={
                "verbose_name": "Work List Answer",
                "verbose_name_plural": "Work List Answers",
            },
        ),
        migrations.CreateModel(
            name="QuestionsABCModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "ABC Model Question",
                "verbose_name_plural": "ABC Model Questions",
            },
        ),
        migrations.CreateModel(
            name="QuestionsWorkList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Work List Question",
                "verbose_name_plural": "Work List Questions",
            },
        ),
        migrations.CreateModel(
            name="TGUser",
            fields=[
                (
                    "user_id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Telegram User ID",
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Telegram Username"
                    ),
                ),
            ],
            options={
                "verbose_name": "TGUser",
                "verbose_name_plural": "TGUsers",
            },
        ),
    ]
