# Generated by Django 4.2.3 on 2023-07-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_questionsabcmodel_text_questionsworklist_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsabcmodel",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="questionsworklist",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
